const menuFilters = [
  { id: "all", label: { en: "All", am: "ሁሉም" } },
  { id: "breakfast", label: { en: "Breakfast", am: "ቁርስ" } },
  { id: "lunch", label: { en: "Lunch", am: "ምሳ" } },
  { id: "fasting", label: { en: "Fasting", am: "የጾም" } },
  { id: "nonFasting", label: { en: "Non-fasting", am: "የፍስክ" } },
  { id: "drinks", label: { en: "Drinks", am: "መጠጦች" } },
  { id: "hotDrinks", label: { en: "Hot Drinks", am: "ትኩስ መጠጦች" } },
];

const categoryLabels = {
  breakfast: { en: "Breakfast", am: "ቁርስ" },
  lunch: { en: "Lunch", am: "ምሳ" },
  dinner: { en: "Dinner", am: "እራት" },
  drinks: { en: "Drinks", am: "መጠጦች" },
  hotDrinks: { en: "Hot Drinks", am: "ትኩስ መጠጦች" },
  specials: { en: "Specials", am: "ልዩ ምግቦች" },
};

const dietLabels = {
  fasting: { en: "Fasting", am: "የጾም" },
  nonFasting: { en: "Non-fasting", am: "የፍስክ" },
};

const drinkTypeLabels = {
  hot: { en: "Hot drink", am: "ትኩስ መጠጥ" },
  cold: { en: "Cold drink", am: "ቀዝቃዛ መጠጥ" },
  beer: { en: "Beer", am: "ቢራ" },
  spirit: { en: "Spirit", am: "መጠጥ" },
  wine: { en: "Wine", am: "ወይን" },
  water: { en: "Water", am: "ውሃ" },
  soft: { en: "Soft drink", am: "ለስላሳ" },
};

function foodItem(category, englishName, amharicName, price, fasting, options = {}) {
  return {
    category,
    englishName,
    amharicName,
    englishDescription: options.englishDescription || "",
    amharicDescription: options.amharicDescription || "",
    price: `${price} ETB`,
    fasting,
    popular: Boolean(options.popular),
  };
}

function drinkItem(englishName, amharicName, price, drinkType, options = {}) {
  return {
    category: drinkType === "hot" ? "hotDrinks" : "drinks",
    englishName,
    amharicName,
    englishDescription: options.englishDescription || "",
    amharicDescription: options.amharicDescription || "",
    price: `${price} ETB`,
    drinkType,
    popular: Boolean(options.popular),
  };
}

// Prices were migrated from "Damu Menu 4 PRT MIAZIA 2018.xlsx".
// Update names, descriptions, and prices here when Damu Hotel changes the printed menu.
const menuItems = [
  foodItem("specials", "Damu Special", "ዳሙ ስፔሻል", 2200, false, { popular: true }),
  foodItem("dinner", "Special Kitfo", "ክትፎ ስፔሻል", 900, false, { popular: true }),
  foodItem("dinner", "Normal Kitfo", "ክትፎ ኖርማል", 800, false),
  foodItem("dinner", "Gored Gored", "ጎረድ ጎረድ", 800, false),
  foodItem("dinner", "Kitfo with Cheese Mix", "ክትፎና አይብ ቅልቅል", 700, false),
  foodItem("breakfast", "Quanta Firfir", "ቋንጣ ፍርፍር", 700, false),
  foodItem("dinner", "Tibs Teferesho", "ጥብስ ተፈርሾ", 700, false, { popular: true }),
  foodItem("dinner", "Lamb or Goat Tibs", "የበግ/የፍየል ጥብስ", 700, false),
  foodItem("dinner", "Chikna Tibs", "የጭቅና ጥብስ", 600, false),
  foodItem("lunch", "Zimamujet", "ዝማሙጀት", 450, false),
  foodItem("breakfast", "Special Firfir", "ስፔሻል ፍርፍር", 450, false),
  foodItem("lunch", "Special Rice", "ስፔሻል ሩዝ", 450, false),
  foodItem("lunch", "Special Pasta", "ስፔሻል ፓስታ", 450, false),
  foodItem("dinner", "Bula with Kitfo", "ቡላ በክትፎ", 650, false),
  foodItem("breakfast", "Special Chechebsa", "ስፔሻል ጨጨብሳ", 500, false),
  foodItem("dinner", "Doro Wot", "ዶሮ ወጥ", 800, false),
  foodItem("lunch", "Gomen Kitfo Non-fasting", "ጎመን ክትፎ የፍስክ", 450, false),
  foodItem("lunch", "Egg with Meat", "እንቁላል በስጋ", 500, false),
  foodItem("lunch", "Tegabino with Butter", "ተጋቢኖ በቅቤ", 400, false),
  foodItem("lunch", "Pasta with Egg", "ፓስታ በእንቁላል", 400, false),
  foodItem("lunch", "Pasta with Meat", "ፓስታ በስጋ", 450, false),
  foodItem("lunch", "Rice with Meat", "ሩዝ በስጋ", 450, false),
  foodItem("lunch", "Vegetables with Meat", "አትክልት በስጋ", 450, false),
  foodItem("lunch", "Bozena Shiro", "ቦዘና ሽሮ", 450, false),
  foodItem("lunch", "Shiro with Butter", "ሽሮ በቅቤ", 400, false),
  foodItem("breakfast", "Firfir with Butter", "ፍርፍር በቅቤ", 400, false),
  foodItem("breakfast", "Egg Firfir", "እንቁላል ፍርፍር", 350, false),
  foodItem("breakfast", "Egg Silsi", "እንቁላል ስልስ", 350, false),
  foodItem("breakfast", "Egg Sandwich", "ሳንድዊች የእንቁላል", 350, false),
  foodItem("breakfast", "Special Ful", "ስፔሻል ፉል", 350, false),
  foodItem("breakfast", "Egg Omelet", "እንቁላል ኦምሌት", 350, false),
  foodItem("dinner", "Dulet", "ዱለት", 400, false),
  foodItem("breakfast", "Special Omelet", "ስፔሻል ኦምሌት", 500, false),

  foodItem("lunch", "Fish Goulash", "ዓሳ ጉላሽ", 600, true),
  foodItem("lunch", "Fish Cutlet", "ዓሳ ኮትሌት", 600, true),
  foodItem("lunch", "Fish Lebleb", "ዓሳ ለብለብ", 600, true),
  foodItem("lunch", "Fasting Gomen Kitfo", "ጎመን ክትፎ የጾም", 400, true),
  foodItem("specials", "Fasting Agelgil", "የጾም አገልግል", 400, true, { popular: true }),
  foodItem("breakfast", "Normal Chechebsa", "ኖርማል ጨጨብሳ", 350, true),
  foodItem("breakfast", "Dirkosh Firfir", "ድርቆሽ ፍርፍር", 350, true),
  foodItem("lunch", "Normal Vegetables", "አትክልት ኖርማል", 300, true),
  foodItem("lunch", "Pasta with Tomato Sauce", "ፓስታ በቲማቲም ሶስ", 300, true),
  foodItem("lunch", "Pasta with Vegetables", "ፓስታ በአትክልት", 300, true),
  foodItem("lunch", "Tegabino", "ተጋቢኖ", 350, true),
  foodItem("lunch", "Normal Rice", "ኖርማል ሩዝ", 300, true),
  foodItem("breakfast", "Normal Bula", "ኖርማል ቡላ (ለብቻውን)", 350, true),
  foodItem("breakfast", "Telba Fitfit", "ተልባ ፍትፍት", 300, true),
  foodItem("breakfast", "Suf Fitfit", "ሱፍ ፍትፍት", 300, true),
  foodItem("breakfast", "Fasting Firfir", "የጾም ፍርፍር", 300, true),
  foodItem("lunch", "Shiro Feses", "ሽሮ ፈሰስ", 300, true, { popular: true }),
  foodItem("lunch", "Tomato Silsi / Lebleb / Kurt", "ቲማቲም ስልስ/ለብለብ/ቁርጥ", 250, true),
  foodItem("lunch", "Fasting Beyaynet", "የጾም በያይነት", 300, true, { popular: true }),
  foodItem("breakfast", "Normal Ful", "ፉል ኖርማል", 250, true),
  foodItem("specials", "Haf Haf Special Fasting Meal", "ሀፍ ሀፍ ልዩ የፆም ምግብ", 300, true),
  foodItem("lunch", "Extra Kocho", "ቆጮ ጭማሪ", 35, true),
  foodItem("lunch", "Extra Injera", "እንጀራ ጭማሪ", 20, true),
  foodItem("lunch", "Extra Bread", "ዳቦ ጭማሪ", 20, true),

  drinkItem("Arada Beer", "አራዳ ቢራ", 110, "beer"),
  drinkItem("Bedele Choice", "በደሌ ቾይዝ", 110, "beer"),
  drinkItem("Heineken Beer", "ሄኒከን ቢራ", 110, "beer"),
  drinkItem("Meta Large Beer", "ሜታ ትልቁ ቢራ", 110, "beer"),
  drinkItem("Large Castel", "ትልቁ ካስትል", 110, "beer"),
  drinkItem("St. George 500ml", "ጊዮርጊስ 500ml", 110, "beer"),
  drinkItem("Harar Beer", "ሐረር ቢራ", 100, "beer"),
  drinkItem("Large Harar", "ትልቁ ሐረር", 110, "beer"),
  drinkItem("Castel Beer", "ካስትል ቢራ", 100, "beer"),
  drinkItem("St. George 330ml", "ጊዮርጊስ 330ml", 100, "beer"),
  drinkItem("Walia 500ml", "ዋልያ 500ml", 100, "beer"),
  drinkItem("Habesha Beer", "ሀበሻ ቢራ", 100, "beer"),
  drinkItem("Dashen Beer", "ዳሽን ቢራ", 100, "beer"),
  drinkItem("Normal Bedele", "ኖርማል በደሌ", 100, "beer"),
  drinkItem("Special Bedele", "ስፔሻል በደሌ", 100, "beer"),
  drinkItem("Nigusu Beer", "ንጉሱ ቢራ", 100, "beer"),
  drinkItem("Meta Beer", "ሜታ ቢራ", 100, "beer"),
  drinkItem("Bikler Beer", "በክለር ቢራ", 100, "beer"),
  drinkItem("Seven Beer", "ሰቨን ቢራ", 100, "beer"),
  drinkItem("Anbessa Beer", "አንበሳ ቢራ", 90, "beer"),
  drinkItem("Walia 330ml", "ዋልያ 330ml", 90, "beer"),
  drinkItem("Sinq Beer", "ስንቅ ቢራ", 90, "beer"),
  drinkItem("Harar Sofi", "ሐረር ሶፊ", 90, "beer"),
  drinkItem("Birtat Beer", "ብርታት ቢራ", 90, "beer"),
  drinkItem("Balageru Beer", "ባላገሩ ቢራ", 90, "beer"),
  drinkItem("Feta Beer", "ፈታ ቢራ", 90, "beer"),
  drinkItem("Coca-Cola", "ኮካ ኮላ", 55, "soft"),
  drinkItem("Pepsi", "ፔፕሲ", 55, "soft"),
  drinkItem("Ambo Water", "አምቦ ውሃ", 55, "water"),
  drinkItem("Cool Water", "ኩል ውሃ", 55, "water"),
  drinkItem("Water 2 Liter", "ውሃ 2 ሊትር", 70, "water"),
  drinkItem("Water 1 Liter", "ውሃ 1 ሊትር", 60, "water"),
  drinkItem("Water 0.5 Liter", "ውሃ 0.5 ሊትር", 40, "water"),
  drinkItem("Gouder Large", "ጉደር ትልቅ", 650, "wine"),
  drinkItem("Awash Large", "አዋሽ ትልቅ", 650, "wine"),
  drinkItem("Acacia Wine", "አኬዥያ ወይን", 1700, "wine"),
  drinkItem("Kemila Wine", "ከሚላ ወይን", 1000, "wine"),
  drinkItem("Aksumite Wine Full", "አክሱሚት ወይን (ሙሉ)", 850, "wine"),
  drinkItem("Gold Label Bottle", "ጎልድ ሌብል በጠርሙስ", 22000, "spirit"),
  drinkItem("Double Black Bottle", "ደብል ብላክ በጠርሙስ", 19500, "spirit"),
  drinkItem("Black Label Bottle", "ብላክ ሌብል በጠርሙስ", 15000, "spirit"),
  drinkItem("Red Label Bottle", "ሬድ ሌብል በጠርሙስ", 8000, "spirit"),
  drinkItem("White Horse Bottle", "ዋይት ሆርስ በጠርሙስ", 8000, "spirit"),
  drinkItem("Gordon's Gin Bottle", "ጎርደንስ ጂን በጠርሙስ", 9000, "spirit"),
  drinkItem("Absolut Vodka", "ቮድካ አብሶሉት", 4500, "spirit"),
  drinkItem("Winter Palace", "ዊንተርፓላስ", 4000, "spirit"),
  drinkItem("Black Label Measure", "ብላክ ሌብል በመለኪያ", 800, "spirit"),
  drinkItem("Red Label Measure", "ሬድ ሌብል በመለኪያ", 500, "spirit"),
  drinkItem("White Horse Measure", "ዋይት ሆርስ በመለኪያ", 500, "spirit"),
  drinkItem("Gordon's Measure", "ጎርደንስ በመለኪያ", 500, "spirit"),
  drinkItem("Mini Gin", "ሚኒ ጂን", 350, "spirit"),

  drinkItem("Jebena Coffee", "የጀበና ቡና", 40, "hot", { popular: true }),
  drinkItem("Jebena Coffee with Butter", "የጀበና ቡና በቅቤ", 75, "hot"),
  drinkItem("Tea", "ሻይ", 80, "hot", { popular: true }),
  drinkItem("Kishir", "ቅሽር", 35, "hot"),
  drinkItem("Espresso", "እስፕሪስ", 50, "hot"),
  drinkItem("Macchiato", "ማኪያቶ", 60, "hot"),
  drinkItem("Loz", "ለውዝ", 70, "hot"),
  drinkItem("Lemon Tea", "የሎሚ ሸይ", 40, "hot"),
  drinkItem("Milk Safi", "ወተት ሳፊ", 70, "hot"),
  drinkItem("Black Coffee", "ቡና እንደወረደ", 60, "hot"),
  drinkItem("Fruit Tea", "የፍራፍሬ ሻይ", 75, "hot"),
  drinkItem("Special Tea", "እስፔሻል ሻይ", 80, "hot"),
  drinkItem("Fasting Macchiato", "የፆም ማኪያቶ", 70, "hot"),
  drinkItem("Ranger", "ሬንጀር", 70, "hot"),
  drinkItem("Kishir with Tea", "ቅሽር በሻይ", 35, "hot"),
  drinkItem("Loz with Kishir", "ለውዝ በቅሽር", 70, "hot"),
  drinkItem("Zebra Macchiato", "ዜብራ ማኪያቶ", 70, "hot"),
  drinkItem("Buna Be'anatu", "ቡና በአናቱ", 60, "hot"),
  drinkItem("Milk with Loz", "ወተት በለውዝ", 100, "hot"),
  drinkItem("Milk with Kishir", "ወተት በቅሽር", 80, "hot"),
  drinkItem("Loz with Coffee", "ለውዝ በቡና", 80, "hot"),
  drinkItem("Teyim Tea", "ጠይም ሻይ", 40, "hot"),
  drinkItem("Thin Tea", "ቀጭን ሻይ", 30, "hot"),
  drinkItem("Milk with Tea", "ወተት በሻይ", 70, "hot"),
  drinkItem("Milk with Coffee", "ወተት በቡና", 90, "hot"),
  drinkItem("Cappuccino", "ካፑቹኖ", 80, "hot"),
];
